create a list of size n,with random numbers from 0 to 100

In [1]:
from random import randint

n = int(input("Size of List:")) # size of list
x = []                          # empty list
for i in range(n):
    val = randint(1,100)    # random num between 1 and 100
    x.append(val)  # add value to list
print(x)

[34, 14, 39, 61, 15, 85, 99, 28, 89, 21, 98, 84, 100, 16, 73, 78, 35, 22, 35, 6, 12, 59, 20, 97, 76, 25, 18, 82, 98, 93, 86, 58, 15, 67, 76, 42, 21, 32, 45, 61, 27, 84, 60, 39, 26, 92, 52, 55, 87, 74, 85, 15, 51, 87, 77, 60, 85, 58, 5, 26, 45, 92, 40, 95, 35, 9, 91, 83, 60, 58, 94, 60, 6, 21, 80, 6, 62, 5, 41, 62, 62, 53, 9, 10, 3, 35, 63, 23, 38, 92, 7, 82, 44, 73, 59, 88, 36, 88, 73, 99, 72, 39, 49, 80, 39, 9, 12, 33, 28, 32, 23, 33, 80, 68, 23, 14, 98, 2, 22, 48, 23, 29, 13, 18, 13, 20, 59, 16, 62, 64, 30, 39, 86, 93, 15, 5, 67, 20, 64, 9, 87, 78, 72, 59, 22, 92, 62, 27, 6, 3, 72, 4, 73, 72, 34, 23, 50, 31, 78, 84, 69, 3, 82, 53, 69, 9, 53, 39, 38, 86, 82, 27, 29, 95, 13, 98, 43, 97, 51, 41, 31, 34, 18, 92, 22, 12, 19, 88, 9, 50, 74, 52, 19, 82, 20, 14, 35, 6, 85, 65, 95, 90, 91, 61, 81, 51, 18, 91, 17, 83, 39, 43, 50, 37, 38, 33, 61, 9, 3, 94, 28, 95, 12, 57, 69, 58, 83, 29, 37, 82, 16, 45, 47, 10, 90, 83, 47, 6, 66, 62, 20, 9, 59, 23, 11, 91, 39, 75, 71, 70, 27, 64, 44, 32, 35, 7, 34, 85, 38, 13, 80, 58, 19, 88, 35, 35, 22, 96, 80, 55, 17, 48, 21, 17, 32, 94, 73, 55, 17, 41, 62, 95, 7, 15, 14, 83, 20, 34, 99, 77, 56, 5, 25, 60, 71, 73, 5, 16, 68, 83, 31, 78, 54, 11, 35, 95, 85, 72, 84, 52, 70, 25, 34, 18, 65, 22, 43, 15, 55, 85, 27, 76, 71, 74, 59, 52, 34, 60, 74, 43, 61, 51, 32, 46, 96, 47, 57, 62, 1, 79, 18, 70, 46, 64, 14, 58, 44, 4, 28, 68, 70, 15, 83, 45, 84, 35, 6, 60, 85, 7, 72, 58, 68, 6, 24, 91, 81, 21, 72, 32, 71, 99, 18, 9, 98, 5, 90, 62, 98, 15, 67, 62, 93, 84, 12, 100, 87, 10, 1, 56, 89, 68, 42, 53, 86, 97, 53, 98, 83, 1, 16, 13, 26, 34, 34, 95, 31, 33, 97, 35, 86, 25, 53, 13, 16, 74, 74, 62, 29, 64, 12, 22, 49, 1, 2, 87, 66, 36, 78, 62, 66, 24, 41, 71, 44, 26, 16, 47, 79, 31, 40, 1, 39, 4, 7, 1, 75, 67, 41, 65, 41, 16, 2, 92, 92, 10, 98, 60, 75, 32, 2, 39, 67, 2, 32, 99, 96, 85, 40, 45, 30, 71, 49, 3, 27, 47, 50, 84, 13, 76, 32, 50, 74, 77, 53, 60, 94, 6, 52, 10, 66, 87, 30, 91, 4, 50, 75, 32, 99, 40, 4, 97, 23, 27, 46, 83, 64, 21, 87, 21, 68, 16, 89, 90, 57, 8, 89, 8, 62, 5, 59, 87, 9, 60, 72, 93, 60, 26, 44, 36, 68, 55, 89, 90, 88, 86, 75, 27, 72, 79, 77, 54, 20, 50, 62, 93, 68, 58, 47, 42, 87, 58, 69, 59, 21, 51, 11, 6, 4, 20, 32, 30, 98, 2, 33, 96, 91, 30, 74, 52, 48, 95, 93, 52, 42, 63, 74, 42, 95, 9, 58, 75, 57, 67, 68, 70, 67, 47, 13, 3, 90, 16, 46, 60, 10, 78, 5, 29, 77, 28, 89, 49, 48, 85, 60, 33, 78, 61, 67, 87, 46, 24, 76, 40, 72, 69, 32, 71, 12, 20, 96, 74, 50, 98, 56, 92, 15, 2, 68, 6, 94, 95, 57, 70, 50, 18, 27, 54, 90, 53, 30, 18, 71, 30, 92, 8, 95, 100, 78, 57, 88, 50, 87, 80, 25, 7, 37, 48, 15, 9, 47, 1, 88, 68, 74, 49, 27, 11, 86, 43, 85, 83, 71, 52, 74, 95, 99, 13, 30, 36, 54, 83, 90, 20, 83, 100, 26, 16, 37, 60, 45, 90, 10, 39, 59, 8, 8, 89, 11, 63, 81, 25, 6, 27, 62, 93, 76, 50, 55, 90, 98, 67, 58, 55, 76, 25, 27, 93, 46, 30, 31, 91, 37, 87, 98, 67, 52, 17, 9, 94, 17, 16, 62, 10, 81, 78, 36, 90, 11, 78, 47, 79, 12, 70, 6, 12, 95, 36, 81, 27, 11, 31, 36, 26, 76, 41, 44, 23, 26, 83, 38, 21, 11, 17, 8, 56, 24, 2, 82, 62, 15, 39, 17, 27, 23, 30, 9, 75, 41, 93, 88, 81, 67, 41, 52, 49, 66, 20, 5, 31, 8, 40, 45, 34, 75, 55, 47, 93, 41, 37, 67, 28, 70, 2, 79, 22, 93, 78, 58, 16, 96, 38, 24, 48, 77, 54, 81, 97, 51, 33, 37, 69, 18, 30, 7, 44, 48, 2, 34, 57, 64, 78, 54, 65, 71, 25, 89, 31, 11, 47, 63, 76, 28, 27, 16, 50, 36, 98, 28, 96, 28, 16, 86, 69, 57, 69, 62, 91, 83, 38, 62, 83, 7, 29, 56, 52, 61, 29, 50, 63, 74, 31, 69, 90, 39, 23, 2, 48, 99, 65, 74, 79, 17, 59, 30, 77, 13, 34, 90, 21, 68, 21, 82, 19, 69, 69, 8, 11, 81, 58, 13, 43, 24, 62, 29, 36, 33, 11, 46, 26, 91, 36, 83, 93, 27, 90, 69, 67, 46, 89, 94, 11, 2, 80, 83, 89, 51, 20, 79, 95, 78, 37, 45, 14, 8, 50, 51, 79, 52, 40, 36, 93, 19, 65, 90, 68, 31, 89, 35, 65, 40, 78, 84, 65, 95, 95, 9, 87, 96, 5, 49, 47, 8, 42, 1, 56, 86, 23, 5, 55, 92, 35, 59, 74, 86, 42, 84, 61, 55, 65, 99, 37, 80, 63, 70, 100, 78, 38, 33, 95, 41, 52, 66, 13, 98, 7, 36, 51, 88, 34, 22, 48, 28, 45, 32, 43, 29, 38, 20, 25, 74, 21, 40, 2, 7, 62, 46, 69, 12, 70, 33, 69, 46, 21, 94, 72, 43, 44, 20, 63, 89, 13, 74, 43, 72, 89, 74, 29, 23, 46, 22, 35, 38, 45, 94, 85, 30, 51, 33, 98, 15, 59, 31, 71, 54, 52, 19, 27, 33, 62, 54, 4, 5, 24, 52, 70, 44, 70, 70, 84, 26, 54, 75, 15, 96, 19, 89, 21, 65, 60, 81, 47, 10, 15, 72, 85, 32, 57, 52, 59, 39, 12, 18, 47, 26, 93, 62, 66, 6, 24, 54, 75, 39, 98, 61, 24, 85, 58, 71, 15, 70, 39, 83, 94, 65, 77, 67, 45, 10, 90, 55, 31, 28, 93, 35, 85, 17, 41, 85, 32, 88, 62, 2, 76, 73, 84, 36, 83, 25, 54, 18, 38, 64, 92, 13, 94, 70, 62, 56, 42, 82, 57, 14, 96, 100, 79, 33, 43, 44, 22, 12, 78, 79, 99, 100, 29, 54, 76, 90, 69, 45, 65, 35, 68, 40, 37, 91, 44, 39, 15, 13, 64, 52, 28, 50, 39, 99, 81, 49, 82, 29, 57, 23, 41, 75, 85, 78, 71, 84, 69, 94, 86, 84, 56, 76, 5, 42, 99, 58, 13, 43, 45, 67, 76, 91, 20, 100, 81, 2, 43, 3, 35, 45, 68, 40, 8, 35, 38, 50, 15, 6, 55, 19, 24, 33, 1, 58, 1, 76, 8, 66, 95, 66, 58, 59, 97, 48, 74, 2, 93, 76, 56, 1, 36, 67, 24, 15, 45, 40, 58, 51, 25, 9, 83, 63, 91, 18, 32, 27, 70, 73, 95, 18, 85, 56, 80, 98, 35, 8, 51, 66, 36, 86, 80, 59, 13, 75, 97, 79, 9, 76, 29, 3, 74, 20, 39, 65, 82, 30, 52, 11, 22, 64, 2, 68, 97, 25, 21, 5, 54, 66, 25, 1, 57, 29, 54, 63, 55, 33, 38, 25, 56, 59, 94, 86, 36, 33, 36, 74, 31, 82, 80, 36, 14, 69, 87, 65, 93, 15, 65, 82, 60, 65, 66, 68, 73, 36, 73, 45, 91, 34, 61, 21, 48, 74, 47, 4, 59, 30, 84, 6, 86, 79, 66, 31, 1, 37, 96, 2, 32, 38, 73, 43, 50, 60, 8, 77, 3, 20, 45, 75, 87, 45, 96, 36, 38, 21, 33, 81, 46, 63, 10, 86, 78, 28, 20, 14, 50, 8, 76, 57, 55, 4, 82, 13, 99, 66, 53, 28, 90, 67, 37, 51, 69, 37, 61, 17, 54, 46, 46, 93, 53, 65, 10, 66, 68, 69, 59, 64, 43, 99, 53, 88, 88, 8, 46, 82, 7, 15, 57, 98, 70, 82, 70, 88, 64, 4, 43, 53, 7, 39, 46, 39, 24, 10, 41, 28, 41, 98, 40, 72, 44, 1, 95, 79, 76, 68, 39, 72, 60, 50, 55, 46, 100, 36, 10, 58, 4, 86, 64, 43, 85, 20, 76, 38, 11, 84, 89, 57, 99, 97, 67, 90, 73, 59, 82, 43, 97, 82, 97, 28, 93, 67, 97, 93, 84, 50, 28, 75, 68, 52, 56, 12, 90, 41, 93, 61, 49, 94, 45, 85, 27, 15, 71, 12, 92, 44, 61, 96, 6, 13, 55, 13, 76, 90, 13, 88, 96, 71, 13, 52, 44, 1, 11, 66, 69, 61, 71, 53, 21, 96, 80, 23, 45, 31, 77, 14, 60, 16, 66, 55, 18, 28, 58, 24, 15, 90, 67, 58, 43, 51, 33, 75, 79, 60, 60, 97, 31, 64, 59, 35, 1, 90, 98, 26, 47, 71, 1, 66, 86, 25, 78, 55, 12, 65, 89, 38, 84, 18, 64, 91, 37, 17, 33, 54, 18, 57, 96, 71, 78, 89, 58, 77, 15, 67, 66, 72, 14, 58, 96, 17, 49, 93, 76, 59, 48, 5, 35, 71, 88, 6, 77, 51, 86, 64, 66, 2, 61, 49, 38, 41, 82, 51, 100, 38, 23, 96, 19, 5, 16, 33, 53, 28, 45, 47, 88, 18, 73, 86, 89, 32, 52, 71, 67, 85, 51, 63, 2, 93, 40, 20, 80, 71, 23, 26, 41, 30, 89, 69, 81, 98, 78, 98, 49, 52, 77, 55, 52, 81, 54, 38, 58, 99, 42, 11, 28, 72, 55, 54, 41, 77, 78, 70, 64, 98, 90, 6, 94, 11, 30, 78, 43, 92, 89, 31, 70, 73, 96, 99, 81, 75, 2, 3, 98, 93, 10, 31, 5, 99, 47, 97, 75, 41, 63, 76, 66, 36, 47, 44, 18, 8, 37, 12, 94, 1, 53, 98, 10, 51, 13, 39, 73, 46, 75, 46, 76, 15, 39, 16, 91, 99, 28, 29, 42, 22, 16, 40, 30, 100, 23, 44, 20, 62, 34, 13, 56, 82, 76, 2, 61, 52, 61, 62, 8, 76, 79, 2, 41, 100, 61, 41, 93, 74, 54, 36, 22, 58, 50, 46, 97, 89, 82, 22, 10, 88, 60, 80, 53, 94, 63, 45, 11, 78, 71, 50, 62, 11, 74, 37, 86, 38, 23, 43, 27, 61, 33, 90, 5, 40, 63, 86, 49, 49, 22, 54, 32, 27, 31, 7, 38, 70, 24, 16, 6, 63, 62, 94, 14, 14, 89, 83, 96, 13, 69, 74, 19, 60, 13, 38, 26, 8, 77, 55, 71, 4, 51, 52, 23, 86, 36, 88, 10, 14, 67, 6, 7, 44, 53, 44, 41, 43, 92, 74, 82, 71, 17, 30, 53, 42, 41, 49, 46, 38, 75, 67, 59, 36, 3, 51, 42, 61, 85, 83, 27, 39, 82, 46, 79, 61, 46, 96, 88, 50, 68, 78, 43, 34, 90, 19, 6, 70, 94, 42, 83, 72, 27, 9, 47, 32, 99, 9, 66, 87, 88, 73, 94, 12, 45, 6, 9, 77, 34, 99, 93, 71, 33, 78, 66, 2, 91, 8, 42, 5, 18, 65, 38, 27, 36, 22, 60, 17, 12, 97, 43, 47, 70, 12, 58, 83, 31, 86, 16, 81, 78, 19, 71, 20, 79, 2, 10, 35, 73, 82, 5, 73, 3, 30, 24, 69, 57, 24, 64, 90, 58, 98, 64, 53, 59, 78, 73, 79, 92, 90, 74, 13, 16, 87, 66, 99, 6, 23, 16, 22, 40, 93, 100, 60, 16, 24, 52, 67, 35, 91, 4, 23, 49, 14, 62, 38, 29, 49, 81, 96, 21, 5, 99, 1, 21, 96, 70, 61, 17, 14, 50, 38, 66, 77, 37, 78, 87, 55, 72, 93, 70, 88, 10, 49, 41, 68, 87, 96, 36, 65, 68, 81, 31, 50, 73, 4, 29, 73, 50, 70, 36, 64, 80, 46, 11, 86, 82, 31, 35, 36, 96, 47, 39, 12, 16, 76, 3, 39, 46, 12, 28, 100, 60, 42, 61, 14, 28, 89, 10, 37, 53, 18, 2, 7, 53, 21, 28, 63, 9, 48, 57, 91, 44, 14, 56, 45, 50, 18, 74, 73]

calculate the mean,max,min,sum of the list

In [2]:
sum(x)

109136

In [4]:
total = sum(x)
xmin = min(x)
xmax = max(x)
xmean = max(x)
print("total:",total)
print("Min:" ,xmin)
print("Max:" , xmax)
print("Mean:" ,xmean)

total: 109136
Min: 1
Max: 100
Mean: 100

generate a list of 25 elements then create smaller list of number from that based on 
. number that is divisible by 3
. num that is dived 5
num that is divide by both 3 ans 5

In [8]:
x = list(range(26))
print(x)
xs = []
for i in x:
    if i % 3 == 0 and i % 5 == 0:
        xs.append(i)
    elif i % 3 == 0:
        xs.append(i)  
    elif i % 5 == 0:
         xs.append(i)  
print(xs)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25]

remove every 3rd element from the list from a list of size 25 and display the updated list

In [11]:
x = list(range(26))

for i,v in enumerate(x):
    if i % 3 == 0:
        x.pop(i)
        print(i)

0
3
6
9
12
15
18

In [13]:
x = list(range(1,26))

for i in range(len(x)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [14]:
x = list(range(100,125))
for i,v in enumerate(x):
    if i % 3 == 0:
        x.pop(i)
print(x)

[101, 102, 103, 105, 106, 107, 109, 110, 111, 113, 114, 115, 117, 118, 119, 121, 122, 123]

take names of 10 movies from user & store them in a list,then display the list in a sorted order

In [16]:

movie = []
for uc in range(10):
    uc = input("Enter movie name :")
    movie.append(uc)
movie.sort()
print(movie)

[' bbvjh', ' mbh', ' nbkjbh', 'a n', 'heelo', 'hij', 'hyg', 'jfhgi', 'mjhgyu', 'nnmbgkjh']

create a nested list that contains triplets at each index
[
    [1,2,3],[4,5,6],[7,8,9]
]

In [17]:
x3 =[]
for i in range(5):
    x3.append([i,i,i])
print(x3)

[[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]

In [21]:
outer = []
count = 1
for i in range(1,4):
    inner = []
    for j in range(1,4):
        inner.append(count)
        count+=1
    outer.append(inner)   
print(outer)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]